### ISSUE TITLE
Upgrade the package to V2

### ISSUE THREAD

**Issue by maikol-solis** [AloisJanicek/org-roam-server-light#4]
Hi! 

Org-roam is almost ready to upgrade to a new version. Have you ever considered upgrading this package to the new db scheme?

https://github.com/org-roam/org-roam/pull/1401

Thanks.

**Comment by maikol-solis** [comment]
Running the package in V2 throws this with the debug variable set on `t`

```
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 45250)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/home/maikol/.emacs.d/.local/straight/repos/org-roam-server-light/server.py", line 71, in do_GET
    handler = RoamDataHandler(self.roam_force, org_roam_db)
  File "/home/maikol/.emacs.d/.local/straight/repos/org-roam-server-light/response/roamDataHandler.py", line 30, in __init__
    self.contents = "data: " + self.roam_server_data() + "\n\n"
  File "/home/maikol/.emacs.d/.local/straight/repos/org-roam-server-light/response/roamDataHandler.py", line 50, in roam_server_data
    c.execute(node_query)
sqlite3.OperationalError: no such table: titles
----------------------------------------
```

**Comment by AloisJanicek** [comment]
I just started to migrate to v2 yesterday, I am in the process of fixing org-roam related stuff all around my config, then I will fix the org-roam-server-light, hopefully as soon as over this weekend.

**Comment by maikol-solis** [comment]
Thanks @AloisJanicek. Terrific news! I am looking forward to test the new version. Best.

**Comment by AloisJanicek** [comment]
I apologize for the 1 month delay. so after some consideration I decided to not proceed with upgrading `org-roam-server-light` for the `org-roam v2`, manly because the [org-roam-ui](https://github.com/org-roam/org-roam-ui) is nice, solves the all original performance-related issues of `org-roam-server` and at top of that is super fast and well designed. We should all focus our efforts there instead.
